-- Extraindo dados da tabela 'fornecedores' --

INSERT INTO fornecedores (CodFor, Empresa, Contato, Cargo, Endereco, Cidade, CEP, Pais) VALUES
(1, 'Exotic Liquids', 'Charlotte Cooper', 'Gerente de Encomendas', '49 Gilbert St.', 'London', 'EC1 4SD', 'Reino Unido'),
(2, 'Exotic Liquids', 'Charlotte Cooper', 'Gerente de Encomendas', '49 Gilbert St.', 'London', 'EC1 4SD', 'Reino Unido'),
(3, 'New Orleans Cajun Delights', 'Shelley Burke', 'Administrador de Pedidos', 'P.O. Box 78934', 'New Orleans', '70117', 'EUA'),
(4, 'Grandma Kelly s Homestead', 'Regina Murphy', 'Representante de Vendas', '707 Oxford Rd.', 'Ann Arbor', '48104', 'EUA'),
(5, 'Tokyo Traders', 'Yoshi Nagase', 'Gerente de Marketing', '9-8 SekimaiMusashino-shi', 'Tokyo', '100', 'Japão'),
(6, 'Cooperativa de Quesos  Las Cabras ', 'Antonio del Valle Saavedra ', 'Administrador de Exportação', 'Calle del Rosal 4', 'Oviedo', '33007', 'Espanha'),
(7, 'Mayumi s', 'Mayumi Ohno', 'Representante de Marketing', '92 Setsuko Chuo-ku', 'Osaka', '545', 'Japão'),
(8, 'Pavlova, Ltd.', 'Ian Devling', 'Gerente de Marketing', '74 Rose St.Moonie Ponds', 'Melbourne', '3058', 'Austrália'),
(9, 'Specialty Biscuits, Ltd.', 'Peter Wilson', 'Representante de Vendas', '29 King s Way', 'Manchester', 'M14 GSD', 'Reino Unido'),
(10, 'PB Knäckebröd AB', 'Lars Peterson', 'Agente de Vendas', 'Kaloadagatan 13', 'Göteborg', 'S-345 67', 'Suécia'),
(11, 'Refrescos Americanas LTDA', 'Carlos Diaz', 'Gerente de Marketing', 'Av. das Americanas 12.890', 'São Paulo', '5442', 'Brasil'),
(12, 'Heli Süßwaren GmbH & Co. KG', 'Petra Winkler', 'Gerente de Vendas', 'Tiergartenstraße 5', 'Berlin', '10785', 'Alemanha'),
(13, 'Plutzer Lebensmittelgroßmärkte AG', 'Martin Bein', 'Ger. Marketing Internacional', 'Bogenallee 51', 'Frankfurt', '60439', 'Alemanha'),
(14, 'Nord-Ost-Fisch Handelsgesellschaft mbH', 'Sven Petersen', 'Coord. Mercados Estrangeiros', 'Frahmredder 112a', 'Cuxhaven', '27478', 'Alemanha'),
(15, 'Formaggi Fortini s.r.l.', 'Elio Rossi', 'Representante de Vendas', 'Viale Dante, 75', 'Ravenna', '48100', 'Itália'),
(16, 'Norske Meierier', 'Beate Vileid', 'Gerente de Marketing', 'Hatlevegen 5', 'Sandvika', '1320', 'Noruega'),
(17, 'Bigfoot Breweries', 'Cheryl Saylor', 'Rep. Financeiro Local', '3400 - 8th AvenueSuite 210', 'Bend', '97101', 'EUA'),
(18, 'Svensk Sjöföda AB', 'Michael Björn', 'Representante de Vendas', 'Brovallavägen 231', 'Stockholm', 'S-123 45', 'Suécia'),
(19, 'Aux joyeux ecclésiastiques', 'Guylène Nodier', 'Gerente de Vendas', '203, Rue des Francs-Bourgeois', 'Paris', '75004', 'França'),
(20, 'New England Seafood Cannery', 'Robb Merchant', 'Agente Financeiro de Atacado', 'Order Processing Dept.2100 Paul Revere Blvd.', 'Boston', '02134', 'EUA'),
(21, 'Leka Trading', 'Chandra Leka', 'Proprietário', '471 Serangoon Loop, Suite #402', 'Singapore', '0512', 'Cingapura'),
(22, 'Lyngbysild', 'Niels Petersen', 'Gerente de Vendas', 'LyngbysildFiskebakken 10', 'Lyngby', '2800', 'Dinamarca'),
(23, 'Zaanse Snoepfabriek', 'Dirk Luchte', 'Gerente Financeiro', 'VerkoopRijnweg 22', 'Zaandam', '9999 ZZ', 'Paises Baixos'),
(24, 'Karkki Oy', 'Anne Heikkonen', 'Gerente do Produto', 'Valtakatu 12', 'Lappeenranta', '53120', 'Finlândia'),
(25, 'G day, Mate', 'Wendy Mackenzie', 'Representante de Vendas', '170 Prince Edward ParadeHunter s Hill', 'Sydney', '2042', 'Austrália'),
(26, 'Ma Maison', 'Jean-Guy Lauzon', 'Gerente de Marketing', '2960 Rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canadá'),
(27, 'Pasta Buttini s.r.l.', 'Giovanni Giudici', 'Administrador de Pedidos', 'Via dei Gelsomini, 153', 'Salerno', '84100', 'Itália'),
(28, 'Escargots Nouveaux', 'Marie Delamare', 'Gerente de Vendas', '22, rue H. Voiron', 'Montceau', '71300', 'França'),
(29, 'Gai pâturage', 'Eliane Noz', 'Representante de Vendas', 'Bat. B3, rue des Alpes', 'Annecy', '74000', 'França'),
(30, 'Forêts d érables', 'Chantal Goulet', 'Gerente Financeiro', '148 rue Chasseur', 'Ste-Hyacinthe', 'J2S 7S8', 'Canadá');